env:
  contexts:
    - name: test
      urls:
        - "http://localhost:3000"
      includePaths:
        - "http://localhost:3000.*"
  parameters:
    failOnError: true
    progressToStdout: true
jobs:
  - type: report
    parameters:
      template: risk-confidence-html
      reportDir: /zap/wrk
      reportFile: "zap-report"
      reportTitle: "ZAP Scan Report"
