name: Release

on:
  push:
    branches: ['main', 'chore/test-monorepo']

jobs:
  static-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-npm.yml@main
    permissions:
      security-events: write
    with:
      matrix_commands: '["start"]'

  tests-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-npm.yml@main
    permissions:
      pull-requests: write
    with:
      docker_compose_file: ''
      npm_build_command: 'npm run start'
      tests: '["test:init"]'

  tests-e2e-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-e2e-npm.yml@main
    permissions: {}
    with:
      docker_compose_file: ''
      pre_test_command: 'npm ci && npx playwright install-deps && npx playwright install'
      test_command: 'E2E_TARGET=node npm run test:playwright || exit 1'

  migration-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/migration-checks-npm.yml@ENG-313-migration-checks
    permissions:
      contents: read
    with:
      seed_command: 'npm run db:seed'

  migration-checks-poetry:
    uses: digicatapult/shared-workflows/.github/workflows/migration-checks-poetry.yml@ENG-313-migration-checks
    permissions:
      contents: read

  build-docker-portal:
    uses: digicatapult/shared-workflows/.github/workflows/build-docker.yml@feat/monorepo-releases
    needs: [static-checks-npm, tests-npm, tests-e2e-npm, migration-checks-npm, migration-checks-poetry]
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      docker_file: portal/Dockerfile
      image_name: hello-world-portal
      scan_container: true
      push_ghcr: true
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.SQNC_DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.SQNC_DOCKERHUB_USERNAME }}

  build-docker-worker:
    uses: digicatapult/shared-workflows/.github/workflows/build-docker.yml@feat/monorepo-releases
    needs: [static-checks-npm, tests-npm, tests-e2e-npm, migration-checks-npm, migration-checks-poetry]
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      docker_file: worker/Dockerfile
      image_name: hello-world-worker
      scan_container: true
      push_ghcr: true
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.SQNC_DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.SQNC_DOCKERHUB_USERNAME }}

  generate-sbom-portal:
    uses: digicatapult/shared-workflows/.github/workflows/generate-sbom.yml@feat/monorepo-releases
    permissions: {}
    needs: [build-docker-portal]
    with:
      sbom_output_file: hello-world-portal.cdx.json
      enable_dtrack_project: true
    secrets:
      DTRACK_APIKEY: ${{ secrets.DTRACK_APIKEY }}
      DTRACK_HOSTNAME: ${{ secrets.DTRACK_HOSTNAME }}


  generate-sbom-worker:
    uses: digicatapult/shared-workflows/.github/workflows/generate-sbom.yml@feat/monorepo-releases
    permissions: {}
    needs: [build-docker-worker]
    with:
      sbom_output_file: hello-world-worker.cdx.json
      enable_dtrack_project: true
    secrets:
      DTRACK_APIKEY: ${{ secrets.DTRACK_APIKEY }}
      DTRACK_HOSTNAME: ${{ secrets.DTRACK_HOSTNAME }}

  release-github:
    uses: digicatapult/shared-workflows/.github/workflows/release-github.yml@feat/monorepo-releases
    permissions:
      contents: write
      pull-requests: read
    needs: [build-docker-portal, build-docker-worker, generate-sbom-portal, generate-sbom-worker]
    with:
      get_sbom: true
