name: Release

on:
  push:
    branches: ['main']

jobs:
  generate-custom-scorecard:
    uses: digicatapult/shared-workflows/.github/workflows/generate-security-scorecard.yml@feature/add_ossf_scorecard_callee_workflow
    permissions:
      security-events: write
      id-token: write
    with:
      custom_scan: true
      custom_checks: "Dangerous-Workflow,Maintained,CI-Tests,Signed-Releases,Vulnerabilities,Code-Review,SAST,Branch-Protection,Token-Permissions,License,Pinned-Dependencies,Binary-Artifacts,Security-Policy"
      upload_type: artifact
      results_format: sarif
      results_file: ${{ github.event.repository.name }}-scorecard.sarif
    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}

  static-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-npm.yml@main
    permissions:
      security-events: write
    with:
      matrix_commands: '["start"]'

  tests-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-npm.yml@main
    permissions:
      pull-requests: write
    with:
      docker_compose_file: ''
      npm_build_command: 'npm run start'
      tests: '["test:init"]'

  tests-e2e-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-e2e-npm.yml@main
    permissions: {}
    with:
      docker_compose_file: ''
      pre_test_command: 'npm ci && npx playwright install-deps && npx playwright install'
      test_command: 'npm run test:playwright || exit 1'

  build-docker:
    uses: digicatapult/shared-workflows/.github/workflows/build-docker.yml@main
    needs: [static-checks-npm, tests-npm, tests-e2e-npm]
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      push_dockerhub: false
      push_ghcr: true
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.SQNC_DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.SQNC_DOCKERHUB_USERNAME }}

  generate-sbom-npm:
    uses: digicatapult/shared-workflows/.github/workflows/generate-sbom.yml@main
    permissions: {}
    needs: [build-docker]

  release-github:
    uses: digicatapult/shared-workflows/.github/workflows/release-github.yml@main
    permissions:
      contents: write
      pull-requests: read
    needs: [build-docker, generate-sbom-npm]
    with:
      get_sbom: true
    secrets: inherit
