name: Synchronise all PR Poetry versions

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write

jobs:
  synchronise-trunk-version-poetry:
    uses: digicatapult/shared-workflows/.github/workflows/synchronise-trunk-version-poetry.yml@chore/test_ubuntu_2604_migration
    with:
      trunk-branch: "main"
    secrets:
      bot-id: ${{ secrets.BOT_ID }}
      bot-key: ${{ secrets.BOT_KEY }}
