name: Lint and test

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-version:
    uses: digicatapult/shared-workflows/.github/workflows/check-version.yml@main
    permissions: {}

  static-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-npm.yml@main
    permissions:
      security-events: write
    with:
      matrix_commands: '["start"]'
      enable_semgrep_action: true
      enable_trufflehog_action: true
      semgrep_extra_args: '--config="p/default"'
      semgrep_upload_type: "sarif"
      trufflehog_extra_args: "--results=verified,unknown --log-level=2"

  tests-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-npm.yml@main
    permissions:
      pull-requests: write
    with:
      coverage: false
      docker_compose_file: ''
      npm_build_command: 'npm run start'
      tests: '["test:init"]'

  tests-e2e-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-e2e-npm.yml@main
    permissions: {}
    with:
      docker_compose_file: ''
      pre_test_command: 'npm ci && npx playwright install-deps && npx playwright install'
      test_command: 'E2E_TARGET=node npm run test:playwright || exit 1'

  static-checks-poetry:
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-poetry.yml@main
    permissions:
      security-events: write
      contents: read
      actions: read
    with:
      matrix_commands: '["pylint hello_world index.py tests", "black --check .", "ruff check .", "mypy hello_world/", "bandit -r hello_world"]'
      enable_semgrep_action: true
      enable_trufflehog_action: true
      semgrep_extra_args: '--config="p/default"'
      semgrep_upload_type: "sarif"
      trufflehog_extra_args: "--results=verified,unknown --log-level=2"

  tests-poetry:
    uses: digicatapult/shared-workflows/.github/workflows/tests-poetry.yml@main
    permissions:
      contents: read
    with:
      coverage: true
      docker_compose_file: ''
      tests: '["tests/unit"]'

  tests-e2e-poetry:
    uses: digicatapult/shared-workflows/.github/workflows/tests-e2e-poetry.yml@main
    permissions:
      contents: read
    with:
      docker_compose_file: ''
      setup_node: true
      pre_test_command: 'npm ci && npx playwright install-deps && npx playwright install'
      test_command: 'E2E_TARGET=python npm run test:playwright'

  migration-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/migration-checks-npm.yml@ENG-313-migration-checks
    permissions:
      contents: read
    with:
      seed_command: 'npm run db:seed'

  migration-checks-poetry:
    uses: digicatapult/shared-workflows/.github/workflows/migration-checks-poetry.yml@ENG-313-migration-checks
    permissions:
      contents: read

  build-docker-npm:
    uses: digicatapult/shared-workflows/.github/workflows/build-docker.yml@ENG-314-container-scan
    needs: [static-checks-npm, tests-npm, tests-e2e-npm]
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      docker_file: Dockerfile
      scan_container: true

  build-docker-poetry:
    uses: digicatapult/shared-workflows/.github/workflows/build-docker.yml@ENG-314-container-scan
    needs: [static-checks-poetry, tests-poetry, tests-e2e-poetry]
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      docker_file: Dockerfile.poetry
      scan_container: true

  generate-sbom-npm:
    uses: digicatapult/shared-workflows/.github/workflows/generate-sbom.yml@main
    permissions: {}
    needs: [build-docker-npm]
    with:
      enable_check_version: true
      enable_dtrack_project: true
      sbom_output_file: ${{ github.event.repository.name }}-npm.cdx.json
    secrets:
      DTRACK_APIKEY: ${{ secrets.DTRACK_APIKEY }}
      DTRACK_HOSTNAME: ${{ secrets.DTRACK_HOSTNAME }}

  generate-sbom-poetry:
    uses: digicatapult/shared-workflows/.github/workflows/generate-sbom.yml@main
    permissions: {}
    needs: [build-docker-poetry]
    with:
      package_manager: poetry
      sbom_tool: "@cyclonedx/cdxgen"
      install_python_deps: true
      python_version: "3.14"
      additional_args: "--spec-version 1.5 --type python"
      enable_check_version: true
      enable_dtrack_project: true
      sbom_output_file: ${{ github.event.repository.name }}-poetry.cdx.json
    secrets:
      DTRACK_APIKEY: ${{ secrets.DTRACK_APIKEY }}
      DTRACK_HOSTNAME: ${{ secrets.DTRACK_HOSTNAME }}
