name: Lint and test

on:
  push:
    branches-ignore: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-version:
    uses: digicatapult/shared-workflows/.github/workflows/check-version.yml@feat/ghcr-pull
    permissions: {}

  static-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-npm.yml@feat/ghcr-pull
    permissions:
      security-events: write
    with:
      matrix_commands: '["start"]'
      enable_semgrep_action: true
      enable_trufflehog_action: true
      semgrep_extra_args: '--config="p/default"'
      semgrep_upload_type: "sarif"
      trufflehog_extra_args: "--results=verified,unknown --log-level=2"

  tests-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-npm.yml@feat/ghcr-pull
    permissions:
      pull-requests: write
    with:
      coverage: false
      docker_compose_file: ""
      npm_build_command: "npm run start"
      tests: '["test:init"]'

  tests-e2e-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-e2e-npm.yml@feat/ghcr-pull
    permissions: {}
    with:
      docker_compose_file: ""
      pre_test_command: "npm ci && npx playwright install-deps && npx playwright install"
      test_command: "npm run test:playwright || exit 1"

  build-docker:
    uses: digicatapult/shared-workflows/.github/workflows/build-docker.yml@feat/ghcr-pull
    needs: [static-checks-npm, tests-npm, tests-e2e-npm]
    permissions:
      contents: read
      packages: write
      security-events: write

  generate-sbom-npm:
    uses: digicatapult/shared-workflows/.github/workflows/generate-sbom-npm.yml@feat/ghcr-pull
    permissions: {}
    needs: [build-docker]
    with:
      enable_check_version: true
      enable_dtrack_project: true
      sbom_output_file: ${{ github.event.repository.name }}.cdx.json
    secrets:
      DTRACK_APIKEY: ${{ secrets.DTRACK_APIKEY }}
      DTRACK_HOSTNAME: ${{ secrets.DTRACK_HOSTNAME }}
