name: Lint and test

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-checks-npm:
    permissions:
      security-events: write
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-npm.yml@test/permissions_logic
    with:
      enable_semgrep_action: true
      enable_trufflehog_action: true
      semgrep_extra_args: '--config="p/default"'
      semgrep_upload_type: "sarif"
      trufflehog_extra_args: "--results=verified,unknown --log-level=2"

  build-docker:
    uses: digicatapult/shared-workflows/.github/workflows/build-docker.yml@test/permissions_logic
